### ISSUE TITLE
TLS issue in Samsung Devices 

### ISSUE THREAD

**Issue by dr7866** [vavadiyahiren/xmpp_plugin#115]
Basically i'm facing issue in Samsung Devices all devices working Fine it give exception that :

 Something went wrong while connecting ,make sure the credentials are right and try again: 
W/System.err(29284): org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 5000ms (~5s). While waiting for establishing TLS [XMPPTCPConnection[not-authenticated] (0)]
W/System.err(29284): 	at org.jivesoftware.smack.AbstractXMPPConnection.waitForConditionOrThrowConnectionException(AbstractXMPPConnection.java:731)
W/System.err(29284): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:857)
W/System.err(29284): 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:526)
W/System.err(29284): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnection.connect(FlutterXmppConnection.java:527)
W/System.err(29284): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.initConnection(FlutterXmppConnectionService.java:72)
W/System.err(29284): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.lambda$start$0$org-xrstudio-xmpp-flutter_xmpp-Connection-FlutterXmppConnectionService(FlutterXmppConnectionService.java:93)
W/System.err(29284): 	at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService$$ExternalSyntheticLambda0.run(Unknown Source:2)
in flutter just on every samsung device this show why 

@vavadiyahiren @florisgravendeel @therif @umairrafiq1133

**Comment by dr7866** [comment]
then also when i try to reconnect it says TLS certificate issue why ??

**Comment by shafaqAyyub** [comment]
Facing Same issue .
@florisgravendeel @vavadiyahiren

**Comment by furqonat** [comment]
i also using samsung android 14  and app crash

**Comment by danishrafiqe** [comment]
not a problem use my XMPP package just import

xmpp_plugin:
  git:
    url: https://github.com/danishrafiqe/chat_state_xmpp.git
    ref: main

**Comment by danishrafiqe** [comment]
just please don't push any code in it
