### ISSUE TITLE
Last Seen Issue 

### ISSUE THREAD

**Issue by dr7866** [vavadiyahiren/xmpp_plugin#117]
Basically this is my roaster when i call await xmppConnection?.getLastSeen(userInfoModel.jid ?? "");
it gives me this exception

org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from 653f78101552616c0771d53c@chat.swatitech.com@92.204.170.107: XMPPError: bad-request - modify [Bad value of attribute 'to' in tag qualified by namespace 'jabber:client']
W/System.err(15180): at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:268)
W/System.err(15180): at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:219)
W/System.err(15180): at org.jivesoftware.smackx.iqlast.LastActivityManager.getLastActivity(LastActivityManager.java:241)
W/System.err(15180): at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnection.getLastSeen(FlutterXmppConnection.java:348)
W/System.err(15180): at org.xrstudio.xmpp.flutter_xmpp.FlutterXmppPlugin.onMethodCall(FlutterXmppPlugin.java:774)
W/System.err(15180): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
W/System.err(15180): at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(15180): at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(15180): at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(15180): at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(15180): at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(15180): at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(15180): at android.os.Looper.loop(Looper.java:288)
W/System.err(15180): at android.app.ActivityThread.main(ActivityThread.java:7839)
W/System.err(15180): at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15180): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err(15180): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
D/SMACK (15180): SENT (0):
I/flutter (15180): checkNewFeat getLastSeen {user_jid: [653f78101552616c0771d53c@chat.swatitech.com](mailto:653f78101552616c0771d53c@chat.swatitech.com)} lastSeenTime: -1
I/flutter (15180): User Last Seen : -1

**Comment by jeevan2304** [comment]
@danishrafiqe ,653f78101552616c0771d53c@chat.swatitech.com@92.204.170.107 you can see here that native side of the plugin code appending the host name to the JID Which you send using getlastseen method, so the openfire or your xmpp client doesn't recognize the JID which you have sent so you are facing the error(bad request) even i am facing the same error the plugin side the actual code is this: In android/src/main/java/org/xrstudio/xmpp/flutter_xmpp/Utils/Utils.java
public static String getJidWithDomainName(String jid, String host) {
        return jid.contains(host) ? jid : jid + Constants.SYMBOL_COMPARE_JID + host;
    } @vavadiyahiren is there any solution for this problem????????
