### ISSUE TITLE
Connection crashes on Android 34 due to Broadcast Receivers 

### ISSUE THREAD

**Issue by nivisi** [vavadiyahiren/xmpp_plugin#128]
Hey there 👋

When trying to connect on an Android 34, it throws the following exception:

```
The following PlatformException was thrown while activating platform stream on channel flutter_xmpp/stream:
PlatformException(error, com.example.example: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, null)
```

In code, I can see that the receiver is registered. Still, this happens. What do I need to do to make it work?

---

Full log below:

```
[ +417 ms] D/flutter_xmpp( 8409):  adding listener: 
[   +4 ms] E/EventChannel#flutter_xmpp/stream( 8409): Failed to open event stream
[        ] E/EventChannel#flutter_xmpp/stream( 8409): java.lang.SecurityException: com.example.example: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Parcel.createException(Parcel.java:3041)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Parcel.readException(Parcel.java:3024)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Parcel.readException(Parcel.java:2966)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at org.xrstudio.xmpp.flutter_xmpp.FlutterXmppPlugin.onListen(FlutterXmppPlugin.java:431)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Handler.handleCallback(Handler.java:958)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Looper.loopOnce(Looper.java:205)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Looper.loop(Looper.java:294)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): Caused by: android.os.RemoteException: Remote stack trace:
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:13927)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2720)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Binder.execTransactInternal(Binder.java:1339)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 	at android.os.Binder.execTransact(Binder.java:1275)
[        ] E/EventChannel#flutter_xmpp/stream( 8409): 
[        ] D/flutter_xmpp( 8409):  adding connection listener: 
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): Failed to open event stream
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): java.lang.SecurityException: com.example.example: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Parcel.createException(Parcel.java:3041)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Parcel.readException(Parcel.java:3024)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Parcel.readException(Parcel.java:2966)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at org.xrstudio.xmpp.flutter_xmpp.FlutterXmppPlugin$7.onListen(FlutterXmppPlugin.java:354)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Handler.handleCallback(Handler.java:958)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Looper.loopOnce(Looper.java:205)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.os.Looper.loop(Looper.java:294)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[        ] E/EventChannel#flutter_xmpp/connection_event_stream( 8409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[        ] D/flutter_xmpp( 8409):  adding success listener: 
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): Failed to open event stream
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): java.lang.SecurityException: com.example.example: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Parcel.createException(Parcel.java:3041)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Parcel.readException(Parcel.java:3024)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Parcel.readException(Parcel.java:2966)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at org.xrstudio.xmpp.flutter_xmpp.FlutterXmppPlugin$5.onListen(FlutterXmppPlugin.java:308)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Handler.handleCallback(Handler.java:958)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Looper.loopOnce(Looper.java:205)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.os.Looper.loop(Looper.java:294)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[        ] E/EventChannel#flutter_xmpp/success_event_stream( 8409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[        ] D/flutter_xmpp( 8409):  adding error listener: 
[  +12 ms] E/EventChannel#flutter_xmpp/error_event_stream( 8409): Failed to open event stream
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): java.lang.SecurityException: com.example.example: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Parcel.createException(Parcel.java:3041)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Parcel.readException(Parcel.java:3024)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Parcel.readException(Parcel.java:2966)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at org.xrstudio.xmpp.flutter_xmpp.FlutterXmppPlugin$6.onListen(FlutterXmppPlugin.java:331)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Handler.handleCallback(Handler.java:958)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Handler.dispatchMessage(Handler.java:99)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Looper.loopOnce(Looper.java:205)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.os.Looper.loop(Looper.java:294)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[        ] E/EventChannel#flutter_xmpp/error_event_stream( 8409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[        ] D/flutter_xmpp( 8409):  onMethodCall call: login
[        ] D/flutter_xmpp( 8409):  onCreate(): 
[        ] D/flutter_xmpp( 8409):  onStartCommand(): 
[        ] D/flutter_xmpp( 8409):  Service Start() function called: 
[        ] D/flutter_xmpp( 8409):  initConnection(): 
[        ] D/flutter_xmpp( 8409):  Connection Constructor called: 
```

**Comment by nivisi** [comment]
Hi @vavadiyahiren any chance you can check this issue?

Anyone else has this issue?
