### ISSUE TITLE
Android FATAL EXCEPTION: Smack Reader (0) 

### ISSUE THREAD

**Issue by canibal1** [vavadiyahiren/xmpp_plugin#31]
**When I try to connect the server, I get the following error. I think the problem is in build.gradle
implementation "org.igniterealtime.smack:$smackVersion" originates from this part. But I'm not sure....**

```

[log] didChangeAppLifecycleState() initState
I/er_xmpp_exampl(24997): ProcessProfilingInfo new_methods=1259 is saved saved_to_disk=1 resolve_classes_delay=5000
W/ContextImpl(24997): Failed to ensure /dev/null/Android/data/org.xrstudio.flutter_xmpp_example/files: java.lang.IllegalStateException: Failed to prepare /dev/null/Android/data/org.xrstudio.flutter_xmpp_example/files/: android.os.ServiceSpecificException:  (code -22)
I/flutter (24997): logFilePath: /storage/emulated/0/Android/data/org.xrstudio.flutter_xmpp_example/files
D/flutter_xmpp(24997):  adding listener: 
D/flutter_xmpp(24997):  adding connection listener: 
D/flutter_xmpp(24997):  adding success listener: 
D/flutter_xmpp(24997):  adding error listener: 
D/flutter_xmpp(24997):  onMethodCall call: login
W/Choreographer(24997): Already have a pending vsync event.  There should only be one at a time.
I/flutter (24997): oke
I/flutter (24997): SUCCESS
I/flutter (24997): oke
D/flutter_xmpp(24997):  onCreate(): 
D/flutter_xmpp(24997):  onStartCommand(): 
D/flutter_xmpp(24997):  Service Start() function called: 
D/flutter_xmpp(24997):  initConnection(): 
D/flutter_xmpp(24997):  Connection Constructor called: 
D/flutter_xmpp(24997):  not valid host: 
D/flutter_xmpp(24997):  connect 1 mServiceName: xxxxxx.com mPort: port mUsername: xxxxxx mPassword: xxxxxx mResource:Android
D/flutter_xmpp(24997):  Calling connect(): 
E/libc    (24997): Access denied finding property "net.dns1"
E/libc    (24997): Access denied finding property "net.dns2"
E/libc    (24997): Access denied finding property "net.dns3"
E/libc    (24997): Access denied finding property "net.dns4"
E/libc    (24997): Access denied finding property "net.dns1"
E/libc    (24997): Access denied finding property "net.dns2"
E/libc    (24997): Access denied finding property "net.dns3"
E/libc    (24997): Access denied finding property "net.dns4"
D/SMACK   (24997): SENT (0): <stream:stream xmlns='jabber:client' to='xxxxxxxx.com' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' from='admin@xxxxxxxx.com' xml:lang='en'>
D/SMACK   (24997): RECV (0): <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="xx.xx.xx.xx" id="xxxxxxxxx" xml:lang="en" version="1.0">
E/AndroidRuntime(24997): FATAL EXCEPTION: Smack Reader (0)
E/AndroidRuntime(24997): Process: org.xrstudio.flutter_xmpp_example, PID: 24997
E/AndroidRuntime(24997): java.lang.AssertionError
E/AndroidRuntime(24997): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1047)
E/AndroidRuntime(24997): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:993)
E/AndroidRuntime(24997): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1009)
E/AndroidRuntime(24997): 	at java.lang.Thread.run(Thread.java:764)
[log] didChangeAppLifecycleState()
[log] detachedCallBack()
I/Process (24997): Sending signal. PID: 24997 SIG: 9
```

**Comment by canibal1** [comment]
@vavadiyahiren I think I find the issue. I haven't SSL/TLS  certificate in my ip address. So this is the issue. 

<img width="930" alt="Screen Shot 2022-08-17 at 01 23 47" src="https://user-images.githubusercontent.com/25279532/184995601-332836fb-5f5c-48c7-97d6-bc15efe6be70.png">

I set the value **requireSSLConnection** to false, but I think still return true, or there is a another issue with this property.
 
<img width="932" alt="Screen Shot 2022-08-17 at 01 25 53" src="https://user-images.githubusercontent.com/25279532/184995818-6fd652f3-8bd6-4b4c-aabc-c792e6c48a73.png">

**Comment by vavadiyahiren** [comment]
SSL can't be turned on IP domain that is expected @canibal1 

Either we need  a domain where we can get SSL cert or we can disable the SSL/TLS connection. 

Let me know if you still having the same problem and feel free to reopen this.

**Comment by canibal1** [comment]
Hey,
Thanks for your reply. It was solved when I turned off the ssl requirement on the server. As you said, I need to configure the server and domain for the SSL certificate.
