### ISSUE TITLE
Release Applications Immediately stop

### ISSUE THREAD

**Issue by ArivhaySoft** [vavadiyahiren/xmpp_plugin#5]
I released the application suddenly the application stopped, after I tried `flutter run --release`  it got an error like the one below

```
D/flutter_xmpp(30344):  onMethodCall call: login
D/flutter_xmpp(30344):  onCreate(): 
D/flutter_xmpp(30344):  onStartCommand(): 
D/flutter_xmpp(30344):  Service Start() function called: 
D/flutter_xmpp(30344):  initConnection(): 
D/flutter_xmpp(30344):  Connection Constructor called: 
E/AndroidRuntime(30344): FATAL EXCEPTION: Thread-4
E/AndroidRuntime(30344): Process: com.arivhaysoft.pulsa24jam, PID: 30344
E/AndroidRuntime(30344): java.lang.ExceptionInInitializerError
E/AndroidRuntime(30344):        at j7.m.i(Unknown Source:0)
E/AndroidRuntime(30344):        at j7.d.<clinit>(Unknown Source:0)
E/AndroidRuntime(30344):        at f8.d.y(Unknown Source:0)
E/AndroidRuntime(30344):        at l9.a.h(Unknown Source:0)
E/AndroidRuntime(30344):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.e(Unknown Source:28)
E/AndroidRuntime(30344):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService.b(Unknown Source:0)
E/AndroidRuntime(30344):        at org.xrstudio.xmpp.flutter_xmpp.Connection.FlutterXmppConnectionService$a.run(Unknown Source:15)
E/AndroidRuntime(30344):        at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(30344): Caused by: java.lang.IllegalStateException: Could not parse Smack configuration file
E/AndroidRuntime(30344):        at j7.p.<clinit>(Unknown Source:197)
E/AndroidRuntime(30344):        ... 8 more
E/AndroidRuntime(30344): Caused by: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
E/AndroidRuntime(30344):        at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(30344):        at java.lang.Class.forName(Class.java:454)
E/AndroidRuntime(30344):        at j7.p.a(Unknown Source:1)
E/AndroidRuntime(30344):        at j7.p.b(Unknown Source:34)
E/AndroidRuntime(30344):        at j7.p.d(Unknown Source:39)
E/AndroidRuntime(30344):        at j7.p.c(Unknown Source:6)
E/AndroidRuntime(30344):        at j7.p.<clinit>(Unknown Source:98)
E/AndroidRuntime(30344):        ... 8 more
E/AndroidRuntime(30344): Caused by: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
E/AndroidRuntime(30344):        ... 15 more
D/flutter_xmpp(31465):  onCreate(): 
D/flutter_xmpp(31465):  onDestroy(): 
D/flutter_xmpp(31465):  stop() :
```

I'm just a user and can't contribute, I hope this problem can be solved

**Comment by vavadiyahiren** [comment]
@ArivhaySoft If you are trying to make a android release version you must add progurad rules of the smack lib in your android progurad files or you can disable it.

**Comment by ArivhaySoft** [comment]
Yes, it worked very well by adding the proguard file.

By the way I see the logs are still visible on release how can I disable the logs ? because the user and password are very visible

`I/flutter (27398): futurelogin{user_jid: user@domain.com/resorce, password: xxxxxx host: domain.com port: 5222}`
