### ISSUE TITLE
requestMamMessages error

### ISSUE THREAD

**Issue by mehmetgencdal** [vavadiyahiren/xmpp_plugin#90]
Hi,

```
DateTime date = DateTime(2023, 12, 7, 0, 0, 0);
int end = date.millisecondsSinceEpoch;
date = DateTime(2023, 12, 6, 0, 0, 0);
int start = date.millisecondsSinceEpoch;

await flutterXmpp.requestMamMessages("username@host/Android", "$start", "$end", "100");
```

Returns:

```
D/SMACK   (24604): RECV (1): <iq type='error' id='49nyg-24' to='myusername@host/Android'><error type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
W/System.err(24604): org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPPError: service-unavailable - cancel
W/System.err(24604): 	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:268)
W/System.err(24604): 	at org.jivesoftware.smack.StanzaCollector.nextResultOrThrow(StanzaCollector.java:219)
W/System.err(24604): 	at org.jivesoftware.smackx.mam.MamManager.queryArchivePage(MamManager.java:917)
W/System.err(24604): 	at org.jivesoftware.smackx.mam.MamManager.queryArchive(MamManager.java:900)
W/System.err(24604): 	at org.jivesoftware.smackx.mam.MamManager.queryArchive(MamManager.java:655)
W/System.err(24604): 	at org.xrstudio.xmpp.flutter_xmpp.managers.MAMManager.requestMAM(MAMManager.java:55)
W/System.err(24604): 	at org.xrstudio.xmpp.flutter_xmpp.FlutterXmppPlugin.onMethodCall(FlutterXmppPlugin.java:689)
W/System.err(24604): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/System.err(24604): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(24604): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/System.err(24604): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err(24604): 	at android.os.Handler.handleCallback(Handler.java:958)
W/System.err(24604): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(24604): 	at android.os.Looper.loopOnce(Looper.java:205)
W/System.err(24604): 	at android.os.Looper.loop(Looper.java:294)
W/System.err(24604): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
W/System.err(24604): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(24604): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
W/System.err(24604): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

I have tried solve but I failed. I wonder if a way to fix it.

**Comment by dr7866** [comment]
@mehmetgencdal can you implement typing status event ??

**Comment by mehmetgencdal** [comment]
@dr7866 

Colud you guide me on how I should do it? It could be good if there is any example or I can share my code.

**Comment by mehmetgencdal** [comment]
Problem solved.
